export interface EmojiEntry {
  emoji: string;
  name: string;
  category: EmojiCategory;
}

export type EmojiCategory =
  | "Smileys"
  | "People"
  | "Animals"
  | "Food"
  | "Travel"
  | "Activities"
  | "Objects"
  | "Symbols"
  | "Flags";

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  "Smileys",
  "People",
  "Animals",
  "Food",
  "Travel",
  "Activities",
  "Objects",
  "Symbols",
  "Flags",
] as const;

export const EMOJI_DATA: readonly EmojiEntry[] = [
  // ── Smileys ──────────────────────────────────────────────
  { emoji: "\u{1F600}", name: "grinning face", category: "Smileys" },
  { emoji: "\u{1F603}", name: "grinning face with big eyes", category: "Smileys" },
  { emoji: "\u{1F604}", name: "grinning face with smiling eyes", category: "Smileys" },
  { emoji: "\u{1F601}", name: "beaming face with smiling eyes", category: "Smileys" },
  { emoji: "\u{1F606}", name: "grinning squinting face", category: "Smileys" },
  { emoji: "\u{1F605}", name: "grinning face with sweat", category: "Smileys" },
  { emoji: "\u{1F923}", name: "rolling on the floor laughing", category: "Smileys" },
  { emoji: "\u{1F602}", name: "face with tears of joy", category: "Smileys" },
  { emoji: "\u{1F642}", name: "slightly smiling face", category: "Smileys" },
  { emoji: "\u{1F643}", name: "upside down face", category: "Smileys" },
  { emoji: "\u{1FAE0}", name: "melting face", category: "Smileys" },
  { emoji: "\u{1F609}", name: "winking face", category: "Smileys" },
  { emoji: "\u{1F60A}", name: "smiling face with smiling eyes", category: "Smileys" },
  { emoji: "\u{1F607}", name: "smiling face with halo", category: "Smileys" },
  { emoji: "\u{1F970}", name: "smiling face with hearts", category: "Smileys" },
  { emoji: "\u{1F60D}", name: "heart eyes", category: "Smileys" },
  { emoji: "\u{1F929}", name: "star struck", category: "Smileys" },
  { emoji: "\u{1F618}", name: "face blowing a kiss", category: "Smileys" },
  { emoji: "\u{1F617}", name: "kissing face", category: "Smileys" },
  { emoji: "\u{1F61A}", name: "kissing face with closed eyes", category: "Smileys" },
  { emoji: "\u{1F619}", name: "kissing face with smiling eyes", category: "Smileys" },
  { emoji: "\u{1F60B}", name: "face savoring food", category: "Smileys" },
  { emoji: "\u{1F61B}", name: "face with tongue", category: "Smileys" },
  { emoji: "\u{1F61C}", name: "winking face with tongue", category: "Smileys" },
  { emoji: "\u{1F92A}", name: "zany face", category: "Smileys" },
  { emoji: "\u{1F61D}", name: "squinting face with tongue", category: "Smileys" },
  { emoji: "\u{1F911}", name: "money mouth face", category: "Smileys" },
  { emoji: "\u{1F917}", name: "hugging face", category: "Smileys" },
  { emoji: "\u{1F92D}", name: "face with hand over mouth", category: "Smileys" },
  { emoji: "\u{1F92B}", name: "shushing face", category: "Smileys" },
  { emoji: "\u{1F914}", name: "thinking face", category: "Smileys" },
  { emoji: "\u{1F910}", name: "zipper mouth face", category: "Smileys" },
  { emoji: "\u{1F928}", name: "face with raised eyebrow", category: "Smileys" },
  { emoji: "\u{1F610}", name: "neutral face", category: "Smileys" },
  { emoji: "\u{1F611}", name: "expressionless face", category: "Smileys" },
  { emoji: "\u{1F636}", name: "face without mouth", category: "Smileys" },
  { emoji: "\u{1F60F}", name: "smirking face", category: "Smileys" },
  { emoji: "\u{1F612}", name: "unamused face", category: "Smileys" },
  { emoji: "\u{1F644}", name: "rolling eyes", category: "Smileys" },
  { emoji: "\u{1F62C}", name: "grimacing face", category: "Smileys" },
  { emoji: "\u{1F62E}\u200D\u{1F4A8}", name: "face exhaling", category: "Smileys" },
  { emoji: "\u{1F925}", name: "lying face", category: "Smileys" },
  { emoji: "\u{1F60C}", name: "relieved face", category: "Smileys" },
  { emoji: "\u{1F614}", name: "pensive face", category: "Smileys" },
  { emoji: "\u{1F62A}", name: "sleepy face", category: "Smileys" },
  { emoji: "\u{1F924}", name: "drooling face", category: "Smileys" },
  { emoji: "\u{1F634}", name: "sleeping face", category: "Smileys" },
  { emoji: "\u{1F637}", name: "face with medical mask", category: "Smileys" },
  { emoji: "\u{1F912}", name: "face with thermometer", category: "Smileys" },
  { emoji: "\u{1F915}", name: "face with head bandage", category: "Smileys" },
  { emoji: "\u{1F922}", name: "nauseated face", category: "Smileys" },
  { emoji: "\u{1F92E}", name: "vomiting face", category: "Smileys" },
  { emoji: "\u{1F927}", name: "sneezing face", category: "Smileys" },
  { emoji: "\u{1F975}", name: "hot face", category: "Smileys" },
  { emoji: "\u{1F976}", name: "cold face", category: "Smileys" },
  { emoji: "\u{1F974}", name: "woozy face", category: "Smileys" },
  { emoji: "\u{1F635}", name: "face with crossed out eyes", category: "Smileys" },
  { emoji: "\u{1F92F}", name: "exploding head", category: "Smileys" },
  { emoji: "\u{1F920}", name: "cowboy hat face", category: "Smileys" },
  { emoji: "\u{1F973}", name: "partying face", category: "Smileys" },
  { emoji: "\u{1F978}", name: "disguised face", category: "Smileys" },
  { emoji: "\u{1F60E}", name: "sunglasses face", category: "Smileys" },
  { emoji: "\u{1F913}", name: "nerd face", category: "Smileys" },
  { emoji: "\u{1F9D0}", name: "monocle face", category: "Smileys" },
  { emoji: "\u{1F615}", name: "confused face", category: "Smileys" },
  { emoji: "\u{1F61F}", name: "worried face", category: "Smileys" },
  { emoji: "\u{1F641}", name: "slightly frowning face", category: "Smileys" },
  { emoji: "\u{1F62E}", name: "open mouth face", category: "Smileys" },
  { emoji: "\u{1F62F}", name: "hushed face", category: "Smileys" },
  { emoji: "\u{1F632}", name: "astonished face", category: "Smileys" },
  { emoji: "\u{1F633}", name: "flushed face", category: "Smileys" },
  { emoji: "\u{1F97A}", name: "pleading face", category: "Smileys" },
  { emoji: "\u{1F626}", name: "frowning face with open mouth", category: "Smileys" },
  { emoji: "\u{1F627}", name: "anguished face", category: "Smileys" },
  { emoji: "\u{1F628}", name: "fearful face", category: "Smileys" },
  { emoji: "\u{1F630}", name: "anxious face with sweat", category: "Smileys" },
  { emoji: "\u{1F625}", name: "sad but relieved face", category: "Smileys" },
  { emoji: "\u{1F622}", name: "crying face", category: "Smileys" },
  { emoji: "\u{1F62D}", name: "loudly crying face", category: "Smileys" },
  { emoji: "\u{1F631}", name: "face screaming in fear", category: "Smileys" },
  { emoji: "\u{1F616}", name: "confounded face", category: "Smileys" },
  { emoji: "\u{1F623}", name: "persevering face", category: "Smileys" },
  { emoji: "\u{1F61E}", name: "disappointed face", category: "Smileys" },
  { emoji: "\u{1F613}", name: "downcast face with sweat", category: "Smileys" },
  { emoji: "\u{1F629}", name: "weary face", category: "Smileys" },
  { emoji: "\u{1F62B}", name: "tired face", category: "Smileys" },
  { emoji: "\u{1F624}", name: "face with steam from nose", category: "Smileys" },
  { emoji: "\u{1F621}", name: "pouting face", category: "Smileys" },
  { emoji: "\u{1F620}", name: "angry face", category: "Smileys" },
  { emoji: "\u{1F92C}", name: "face with symbols on mouth", category: "Smileys" },
  { emoji: "\u{1F608}", name: "smiling face with horns", category: "Smileys" },
  { emoji: "\u{1F47F}", name: "angry face with horns", category: "Smileys" },
  { emoji: "\u{1F480}", name: "skull", category: "Smileys" },
  { emoji: "\u{1F4A9}", name: "pile of poo", category: "Smileys" },
  { emoji: "\u{1F921}", name: "clown face", category: "Smileys" },
  { emoji: "\u{1F47B}", name: "ghost", category: "Smileys" },
  { emoji: "\u{1F47D}", name: "alien", category: "Smileys" },
  { emoji: "\u{1F916}", name: "robot", category: "Smileys" },
  { emoji: "\u{1F63A}", name: "grinning cat", category: "Smileys" },
  { emoji: "\u{1F63B}", name: "heart eyes cat", category: "Smileys" },
  { emoji: "\u{1F63D}", name: "kissing cat", category: "Smileys" },
  { emoji: "\u{1F640}", name: "weary cat", category: "Smileys" },
  { emoji: "\u{1F63F}", name: "crying cat", category: "Smileys" },
  { emoji: "\u{1F63E}", name: "pouting cat", category: "Smileys" },

  // ── People ───────────────────────────────────────────────
  { emoji: "\u{1F44B}", name: "waving hand", category: "People" },
  { emoji: "\u{1F91A}", name: "raised back of hand", category: "People" },
  { emoji: "\u{270B}", name: "raised hand", category: "People" },
  { emoji: "\u{1F596}", name: "vulcan salute", category: "People" },
  { emoji: "\u{1F44C}", name: "ok hand", category: "People" },
  { emoji: "\u{1F90C}", name: "pinched fingers", category: "People" },
  { emoji: "\u{1F90F}", name: "pinching hand", category: "People" },
  { emoji: "\u270C\uFE0F", name: "victory hand", category: "People" },
  { emoji: "\u{1F91E}", name: "crossed fingers", category: "People" },
  { emoji: "\u{1FAF0}", name: "hand with index finger and thumb crossed", category: "People" },
  { emoji: "\u{1F91F}", name: "love you gesture", category: "People" },
  { emoji: "\u{1F918}", name: "sign of the horns", category: "People" },
  { emoji: "\u{1F919}", name: "call me hand", category: "People" },
  { emoji: "\u{1F448}", name: "backhand index pointing left", category: "People" },
  { emoji: "\u{1F449}", name: "backhand index pointing right", category: "People" },
  { emoji: "\u{1F446}", name: "backhand index pointing up", category: "People" },
  { emoji: "\u{1F595}", name: "middle finger", category: "People" },
  { emoji: "\u{1F447}", name: "backhand index pointing down", category: "People" },
  { emoji: "\u261D\uFE0F", name: "index pointing up", category: "People" },
  { emoji: "\u{1FAF5}", name: "index pointing at the viewer", category: "People" },
  { emoji: "\u{1F44D}", name: "thumbs up", category: "People" },
  { emoji: "\u{1F44E}", name: "thumbs down", category: "People" },
  { emoji: "\u270A", name: "raised fist", category: "People" },
  { emoji: "\u{1F44A}", name: "oncoming fist", category: "People" },
  { emoji: "\u{1F91B}", name: "left facing fist", category: "People" },
  { emoji: "\u{1F91C}", name: "right facing fist", category: "People" },
  { emoji: "\u{1F44F}", name: "clapping hands", category: "People" },
  { emoji: "\u{1F64C}", name: "raising hands", category: "People" },
  { emoji: "\u{1FAF6}", name: "heart hands", category: "People" },
  { emoji: "\u{1F450}", name: "open hands", category: "People" },
  { emoji: "\u{1F932}", name: "palms up together", category: "People" },
  { emoji: "\u{1F91D}", name: "handshake", category: "People" },
  { emoji: "\u{1F64F}", name: "folded hands", category: "People" },
  { emoji: "\u270D\uFE0F", name: "writing hand", category: "People" },
  { emoji: "\u{1F485}", name: "nail polish", category: "People" },
  { emoji: "\u{1F933}", name: "selfie", category: "People" },
  { emoji: "\u{1F4AA}", name: "flexed biceps", category: "People" },
  { emoji: "\u{1F9B5}", name: "leg", category: "People" },
  { emoji: "\u{1F9B6}", name: "foot", category: "People" },
  { emoji: "\u{1F442}", name: "ear", category: "People" },
  { emoji: "\u{1F443}", name: "nose", category: "People" },
  { emoji: "\u{1F9E0}", name: "brain", category: "People" },
  { emoji: "\u{1F441}\uFE0F", name: "eye", category: "People" },
  { emoji: "\u{1F440}", name: "eyes", category: "People" },
  { emoji: "\u{1F445}", name: "tongue", category: "People" },
  { emoji: "\u{1F444}", name: "mouth", category: "People" },
  { emoji: "\u{1F476}", name: "baby", category: "People" },
  { emoji: "\u{1F9D2}", name: "child", category: "People" },
  { emoji: "\u{1F466}", name: "boy", category: "People" },
  { emoji: "\u{1F467}", name: "girl", category: "People" },
  { emoji: "\u{1F9D1}", name: "person", category: "People" },
  { emoji: "\u{1F468}", name: "man", category: "People" },
  { emoji: "\u{1F469}", name: "woman", category: "People" },
  { emoji: "\u{1F9D3}", name: "older person", category: "People" },
  { emoji: "\u{1F474}", name: "old man", category: "People" },
  { emoji: "\u{1F475}", name: "old woman", category: "People" },
  { emoji: "\u{1F46E}", name: "police officer", category: "People" },
  { emoji: "\u{1F477}", name: "construction worker", category: "People" },
  { emoji: "\u{1F482}", name: "guard", category: "People" },
  { emoji: "\u{1F575}\uFE0F", name: "detective", category: "People" },
  { emoji: "\u{1F469}\u200D\u2695\uFE0F", name: "woman health worker", category: "People" },
  { emoji: "\u{1F468}\u200D\u{1F3EB}", name: "man teacher", category: "People" },
  { emoji: "\u{1F468}\u200D\u{1F4BB}", name: "man technologist", category: "People" },
  { emoji: "\u{1F469}\u200D\u{1F4BB}", name: "woman technologist", category: "People" },
  { emoji: "\u{1F468}\u200D\u{1F680}", name: "man astronaut", category: "People" },
  { emoji: "\u{1F469}\u200D\u{1F680}", name: "woman astronaut", category: "People" },

  // ── Animals ──────────────────────────────────────────────
  { emoji: "\u{1F435}", name: "monkey face", category: "Animals" },
  { emoji: "\u{1F412}", name: "monkey", category: "Animals" },
  { emoji: "\u{1F98D}", name: "gorilla", category: "Animals" },
  { emoji: "\u{1F9A7}", name: "orangutan", category: "Animals" },
  { emoji: "\u{1F436}", name: "dog face", category: "Animals" },
  { emoji: "\u{1F415}", name: "dog", category: "Animals" },
  { emoji: "\u{1F9AE}", name: "guide dog", category: "Animals" },
  { emoji: "\u{1F429}", name: "poodle", category: "Animals" },
  { emoji: "\u{1F43A}", name: "wolf", category: "Animals" },
  { emoji: "\u{1F98A}", name: "fox", category: "Animals" },
  { emoji: "\u{1F99D}", name: "raccoon", category: "Animals" },
  { emoji: "\u{1F431}", name: "cat face", category: "Animals" },
  { emoji: "\u{1F408}", name: "cat", category: "Animals" },
  { emoji: "\u{1F981}", name: "lion", category: "Animals" },
  { emoji: "\u{1F42F}", name: "tiger face", category: "Animals" },
  { emoji: "\u{1F405}", name: "tiger", category: "Animals" },
  { emoji: "\u{1F406}", name: "leopard", category: "Animals" },
  { emoji: "\u{1F434}", name: "horse face", category: "Animals" },
  { emoji: "\u{1F40E}", name: "horse", category: "Animals" },
  { emoji: "\u{1F984}", name: "unicorn", category: "Animals" },
  { emoji: "\u{1F993}", name: "zebra", category: "Animals" },
  { emoji: "\u{1F98C}", name: "deer", category: "Animals" },
  { emoji: "\u{1F9AC}", name: "bison", category: "Animals" },
  { emoji: "\u{1F42E}", name: "cow face", category: "Animals" },
  { emoji: "\u{1F402}", name: "ox", category: "Animals" },
  { emoji: "\u{1F403}", name: "water buffalo", category: "Animals" },
  { emoji: "\u{1F437}", name: "pig face", category: "Animals" },
  { emoji: "\u{1F416}", name: "pig", category: "Animals" },
  { emoji: "\u{1F417}", name: "boar", category: "Animals" },
  { emoji: "\u{1F43D}", name: "pig nose", category: "Animals" },
  { emoji: "\u{1F40F}", name: "ram", category: "Animals" },
  { emoji: "\u{1F411}", name: "ewe", category: "Animals" },
  { emoji: "\u{1F410}", name: "goat", category: "Animals" },
  { emoji: "\u{1F42A}", name: "camel", category: "Animals" },
  { emoji: "\u{1F42B}", name: "two hump camel", category: "Animals" },
  { emoji: "\u{1F999}", name: "llama", category: "Animals" },
  { emoji: "\u{1F992}", name: "giraffe", category: "Animals" },
  { emoji: "\u{1F418}", name: "elephant", category: "Animals" },
  { emoji: "\u{1F9A3}", name: "mammoth", category: "Animals" },
  { emoji: "\u{1F98F}", name: "rhinoceros", category: "Animals" },
  { emoji: "\u{1F99B}", name: "hippopotamus", category: "Animals" },
  { emoji: "\u{1F42D}", name: "mouse face", category: "Animals" },
  { emoji: "\u{1F401}", name: "mouse", category: "Animals" },
  { emoji: "\u{1F400}", name: "rat", category: "Animals" },
  { emoji: "\u{1F439}", name: "hamster", category: "Animals" },
  { emoji: "\u{1F430}", name: "rabbit face", category: "Animals" },
  { emoji: "\u{1F407}", name: "rabbit", category: "Animals" },
  { emoji: "\u{1F43F}\uFE0F", name: "chipmunk", category: "Animals" },
  { emoji: "\u{1F9AB}", name: "beaver", category: "Animals" },
  { emoji: "\u{1F994}", name: "hedgehog", category: "Animals" },
  { emoji: "\u{1F987}", name: "bat", category: "Animals" },
  { emoji: "\u{1F43B}", name: "bear", category: "Animals" },
  { emoji: "\u{1F428}", name: "koala", category: "Animals" },
  { emoji: "\u{1F43C}", name: "panda", category: "Animals" },
  { emoji: "\u{1F9A5}", name: "sloth", category: "Animals" },
  { emoji: "\u{1F9A6}", name: "otter", category: "Animals" },
  { emoji: "\u{1F9A8}", name: "skunk", category: "Animals" },
  { emoji: "\u{1F998}", name: "kangaroo", category: "Animals" },
  { emoji: "\u{1F9A1}", name: "badger", category: "Animals" },
  { emoji: "\u{1F43E}", name: "paw prints", category: "Animals" },
  { emoji: "\u{1F426}", name: "bird", category: "Animals" },
  { emoji: "\u{1F414}", name: "chicken", category: "Animals" },
  { emoji: "\u{1F427}", name: "penguin", category: "Animals" },
  { emoji: "\u{1F54A}\uFE0F", name: "dove", category: "Animals" },
  { emoji: "\u{1F985}", name: "eagle", category: "Animals" },
  { emoji: "\u{1F986}", name: "duck", category: "Animals" },
  { emoji: "\u{1F989}", name: "owl", category: "Animals" },
  { emoji: "\u{1F9A9}", name: "flamingo", category: "Animals" },
  { emoji: "\u{1F438}", name: "frog", category: "Animals" },
  { emoji: "\u{1F40A}", name: "crocodile", category: "Animals" },
  { emoji: "\u{1F422}", name: "turtle", category: "Animals" },
  { emoji: "\u{1F98E}", name: "lizard", category: "Animals" },
  { emoji: "\u{1F40D}", name: "snake", category: "Animals" },
  { emoji: "\u{1F432}", name: "dragon face", category: "Animals" },
  { emoji: "\u{1F409}", name: "dragon", category: "Animals" },
  { emoji: "\u{1F433}", name: "spouting whale", category: "Animals" },
  { emoji: "\u{1F40B}", name: "whale", category: "Animals" },
  { emoji: "\u{1F42C}", name: "dolphin", category: "Animals" },
  { emoji: "\u{1F41F}", name: "fish", category: "Animals" },
  { emoji: "\u{1F420}", name: "tropical fish", category: "Animals" },
  { emoji: "\u{1F421}", name: "blowfish", category: "Animals" },
  { emoji: "\u{1F988}", name: "shark", category: "Animals" },
  { emoji: "\u{1F419}", name: "octopus", category: "Animals" },
  { emoji: "\u{1F41A}", name: "spiral shell", category: "Animals" },
  { emoji: "\u{1F40C}", name: "snail", category: "Animals" },
  { emoji: "\u{1F98B}", name: "butterfly", category: "Animals" },
  { emoji: "\u{1F41B}", name: "bug", category: "Animals" },
  { emoji: "\u{1F41C}", name: "ant", category: "Animals" },
  { emoji: "\u{1F41D}", name: "honeybee", category: "Animals" },
  { emoji: "\u{1FAB2}", name: "beetle", category: "Animals" },
  { emoji: "\u{1F41E}", name: "ladybug", category: "Animals" },

  // ── Food ─────────────────────────────────────────────────
  { emoji: "\u{1F347}", name: "grapes", category: "Food" },
  { emoji: "\u{1F348}", name: "melon", category: "Food" },
  { emoji: "\u{1F349}", name: "watermelon", category: "Food" },
  { emoji: "\u{1F34A}", name: "tangerine", category: "Food" },
  { emoji: "\u{1F34B}", name: "lemon", category: "Food" },
  { emoji: "\u{1F34C}", name: "banana", category: "Food" },
  { emoji: "\u{1F34D}", name: "pineapple", category: "Food" },
  { emoji: "\u{1F96D}", name: "mango", category: "Food" },
  { emoji: "\u{1F34E}", name: "red apple", category: "Food" },
  { emoji: "\u{1F34F}", name: "green apple", category: "Food" },
  { emoji: "\u{1F350}", name: "pear", category: "Food" },
  { emoji: "\u{1F351}", name: "peach", category: "Food" },
  { emoji: "\u{1F352}", name: "cherries", category: "Food" },
  { emoji: "\u{1F353}", name: "strawberry", category: "Food" },
  { emoji: "\u{1FAD0}", name: "blueberries", category: "Food" },
  { emoji: "\u{1F95D}", name: "kiwi", category: "Food" },
  { emoji: "\u{1F345}", name: "tomato", category: "Food" },
  { emoji: "\u{1FAD2}", name: "olive", category: "Food" },
  { emoji: "\u{1F965}", name: "coconut", category: "Food" },
  { emoji: "\u{1F951}", name: "avocado", category: "Food" },
  { emoji: "\u{1F346}", name: "eggplant", category: "Food" },
  { emoji: "\u{1F954}", name: "potato", category: "Food" },
  { emoji: "\u{1F955}", name: "carrot", category: "Food" },
  { emoji: "\u{1F33D}", name: "corn", category: "Food" },
  { emoji: "\u{1F336}\uFE0F", name: "hot pepper", category: "Food" },
  { emoji: "\u{1FAD1}", name: "bell pepper", category: "Food" },
  { emoji: "\u{1F952}", name: "cucumber", category: "Food" },
  { emoji: "\u{1F96C}", name: "leafy green", category: "Food" },
  { emoji: "\u{1F966}", name: "broccoli", category: "Food" },
  { emoji: "\u{1F9C4}", name: "garlic", category: "Food" },
  { emoji: "\u{1F9C5}", name: "onion", category: "Food" },
  { emoji: "\u{1F344}", name: "mushroom", category: "Food" },
  { emoji: "\u{1F95C}", name: "peanuts", category: "Food" },
  { emoji: "\u{1F35E}", name: "bread", category: "Food" },
  { emoji: "\u{1F950}", name: "croissant", category: "Food" },
  { emoji: "\u{1F956}", name: "baguette", category: "Food" },
  { emoji: "\u{1FAD3}", name: "flatbread", category: "Food" },
  { emoji: "\u{1F968}", name: "pretzel", category: "Food" },
  { emoji: "\u{1F96F}", name: "bagel", category: "Food" },
  { emoji: "\u{1F95E}", name: "pancakes", category: "Food" },
  { emoji: "\u{1F9C7}", name: "waffle", category: "Food" },
  { emoji: "\u{1F9C0}", name: "cheese", category: "Food" },
  { emoji: "\u{1F356}", name: "meat on bone", category: "Food" },
  { emoji: "\u{1F357}", name: "poultry leg", category: "Food" },
  { emoji: "\u{1F969}", name: "cut of meat", category: "Food" },
  { emoji: "\u{1F953}", name: "bacon", category: "Food" },
  { emoji: "\u{1F354}", name: "hamburger", category: "Food" },
  { emoji: "\u{1F35F}", name: "french fries", category: "Food" },
  { emoji: "\u{1F355}", name: "pizza", category: "Food" },
  { emoji: "\u{1F32D}", name: "hot dog", category: "Food" },
  { emoji: "\u{1F96A}", name: "sandwich", category: "Food" },
  { emoji: "\u{1F32E}", name: "taco", category: "Food" },
  { emoji: "\u{1F32F}", name: "burrito", category: "Food" },
  { emoji: "\u{1FAD4}", name: "tamale", category: "Food" },
  { emoji: "\u{1F959}", name: "stuffed flatbread", category: "Food" },
  { emoji: "\u{1F9C6}", name: "falafel", category: "Food" },
  { emoji: "\u{1F95A}", name: "egg", category: "Food" },
  { emoji: "\u{1F373}", name: "cooking", category: "Food" },
  { emoji: "\u{1F958}", name: "shallow pan of food", category: "Food" },
  { emoji: "\u{1F372}", name: "pot of food", category: "Food" },
  { emoji: "\u{1F35D}", name: "spaghetti", category: "Food" },
  { emoji: "\u{1F35C}", name: "steaming bowl", category: "Food" },
  { emoji: "\u{1F363}", name: "sushi", category: "Food" },
  { emoji: "\u{1F371}", name: "bento box", category: "Food" },
  { emoji: "\u{1F364}", name: "fried shrimp", category: "Food" },
  { emoji: "\u{1F35B}", name: "curry rice", category: "Food" },
  { emoji: "\u{1F35A}", name: "rice", category: "Food" },
  { emoji: "\u{1F358}", name: "rice cracker", category: "Food" },
  { emoji: "\u{1F369}", name: "doughnut", category: "Food" },
  { emoji: "\u{1F36A}", name: "cookie", category: "Food" },
  { emoji: "\u{1F382}", name: "birthday cake", category: "Food" },
  { emoji: "\u{1F370}", name: "shortcake", category: "Food" },
  { emoji: "\u{1F9C1}", name: "cupcake", category: "Food" },
  { emoji: "\u{1F367}", name: "shaved ice", category: "Food" },
  { emoji: "\u{1F368}", name: "ice cream", category: "Food" },
  { emoji: "\u{1F366}", name: "soft ice cream", category: "Food" },
  { emoji: "\u{1F36B}", name: "chocolate", category: "Food" },
  { emoji: "\u{1F36C}", name: "candy", category: "Food" },
  { emoji: "\u{1F36D}", name: "lollipop", category: "Food" },
  { emoji: "\u{1F36F}", name: "honey", category: "Food" },
  { emoji: "\u2615", name: "hot beverage", category: "Food" },
  { emoji: "\u{1FAD6}", name: "teapot", category: "Food" },
  { emoji: "\u{1F375}", name: "teacup without handle", category: "Food" },
  { emoji: "\u{1F376}", name: "sake", category: "Food" },
  { emoji: "\u{1F37A}", name: "beer mug", category: "Food" },
  { emoji: "\u{1F37B}", name: "clinking beer mugs", category: "Food" },
  { emoji: "\u{1F942}", name: "clinking glasses", category: "Food" },
  { emoji: "\u{1F377}", name: "wine glass", category: "Food" },
  { emoji: "\u{1F378}", name: "cocktail glass", category: "Food" },
  { emoji: "\u{1F379}", name: "tropical drink", category: "Food" },
  { emoji: "\u{1F9CB}", name: "bubble tea", category: "Food" },
  { emoji: "\u{1F9C3}", name: "beverage box", category: "Food" },
  { emoji: "\u{1F964}", name: "cup with straw", category: "Food" },

  // ── Travel ───────────────────────────────────────────────
  { emoji: "\u{1F30D}", name: "globe europe africa", category: "Travel" },
  { emoji: "\u{1F30E}", name: "globe americas", category: "Travel" },
  { emoji: "\u{1F30F}", name: "globe asia australia", category: "Travel" },
  { emoji: "\u{1F5FA}\uFE0F", name: "world map", category: "Travel" },
  { emoji: "\u{1F3D4}\uFE0F", name: "snow capped mountain", category: "Travel" },
  { emoji: "\u26F0\uFE0F", name: "mountain", category: "Travel" },
  { emoji: "\u{1F30B}", name: "volcano", category: "Travel" },
  { emoji: "\u{1F3D6}\uFE0F", name: "beach with umbrella", category: "Travel" },
  { emoji: "\u{1F3DC}\uFE0F", name: "desert", category: "Travel" },
  { emoji: "\u{1F3DD}\uFE0F", name: "desert island", category: "Travel" },
  { emoji: "\u{1F3DE}\uFE0F", name: "national park", category: "Travel" },
  { emoji: "\u{1F3DF}\uFE0F", name: "stadium", category: "Travel" },
  { emoji: "\u{1F3DB}\uFE0F", name: "classical building", category: "Travel" },
  { emoji: "\u{1F3D7}\uFE0F", name: "building construction", category: "Travel" },
  { emoji: "\u{1F3D8}\uFE0F", name: "houses", category: "Travel" },
  { emoji: "\u{1F3E0}", name: "house", category: "Travel" },
  { emoji: "\u{1F3E2}", name: "office building", category: "Travel" },
  { emoji: "\u{1F3E3}", name: "post office", category: "Travel" },
  { emoji: "\u{1F3E5}", name: "hospital", category: "Travel" },
  { emoji: "\u{1F3E8}", name: "hotel", category: "Travel" },
  { emoji: "\u{1F3EA}", name: "convenience store", category: "Travel" },
  { emoji: "\u{1F3EB}", name: "school", category: "Travel" },
  { emoji: "\u{1F3EC}", name: "department store", category: "Travel" },
  { emoji: "\u{1F3ED}", name: "factory", category: "Travel" },
  { emoji: "\u{1F3EF}", name: "japanese castle", category: "Travel" },
  { emoji: "\u{1F3F0}", name: "castle", category: "Travel" },
  { emoji: "\u{1F492}", name: "wedding", category: "Travel" },
  { emoji: "\u{1F5FC}", name: "tokyo tower", category: "Travel" },
  { emoji: "\u{1F5FD}", name: "statue of liberty", category: "Travel" },
  { emoji: "\u26EA", name: "church", category: "Travel" },
  { emoji: "\u{1F54C}", name: "mosque", category: "Travel" },
  { emoji: "\u26F2", name: "fountain", category: "Travel" },
  { emoji: "\u26FA", name: "tent", category: "Travel" },
  { emoji: "\u{1F301}", name: "foggy", category: "Travel" },
  { emoji: "\u{1F303}", name: "night with stars", category: "Travel" },
  { emoji: "\u{1F304}", name: "sunrise over mountains", category: "Travel" },
  { emoji: "\u{1F305}", name: "sunrise", category: "Travel" },
  { emoji: "\u{1F306}", name: "cityscape at dusk", category: "Travel" },
  { emoji: "\u{1F307}", name: "sunset", category: "Travel" },
  { emoji: "\u{1F309}", name: "bridge at night", category: "Travel" },
  { emoji: "\u{1F680}", name: "rocket", category: "Travel" },
  { emoji: "\u{1F6F8}", name: "flying saucer", category: "Travel" },
  { emoji: "\u2708\uFE0F", name: "airplane", category: "Travel" },
  { emoji: "\u{1F681}", name: "helicopter", category: "Travel" },
  { emoji: "\u{1F682}", name: "locomotive", category: "Travel" },
  { emoji: "\u{1F683}", name: "railway car", category: "Travel" },
  { emoji: "\u{1F684}", name: "high speed train", category: "Travel" },
  { emoji: "\u{1F695}", name: "taxi", category: "Travel" },
  { emoji: "\u{1F697}", name: "automobile", category: "Travel" },
  { emoji: "\u{1F699}", name: "sport utility vehicle", category: "Travel" },
  { emoji: "\u{1F68C}", name: "bus", category: "Travel" },
  { emoji: "\u{1F6B2}", name: "bicycle", category: "Travel" },
  { emoji: "\u{1F6F5}", name: "motor scooter", category: "Travel" },
  { emoji: "\u{1F3CD}\uFE0F", name: "motorcycle", category: "Travel" },
  { emoji: "\u{1F6A2}", name: "ship", category: "Travel" },
  { emoji: "\u26F5", name: "sailboat", category: "Travel" },

  // ── Activities ───────────────────────────────────────────
  { emoji: "\u{1F3C6}", name: "trophy", category: "Activities" },
  { emoji: "\u{1F3C5}", name: "sports medal", category: "Activities" },
  { emoji: "\u{1F947}", name: "first place medal", category: "Activities" },
  { emoji: "\u{1F948}", name: "second place medal", category: "Activities" },
  { emoji: "\u{1F949}", name: "third place medal", category: "Activities" },
  { emoji: "\u26BD", name: "soccer ball", category: "Activities" },
  { emoji: "\u26BE", name: "baseball", category: "Activities" },
  { emoji: "\u{1F94E}", name: "softball", category: "Activities" },
  { emoji: "\u{1F3C0}", name: "basketball", category: "Activities" },
  { emoji: "\u{1F3D0}", name: "volleyball", category: "Activities" },
  { emoji: "\u{1F3C8}", name: "american football", category: "Activities" },
  { emoji: "\u{1F3C9}", name: "rugby football", category: "Activities" },
  { emoji: "\u{1F3BE}", name: "tennis", category: "Activities" },
  { emoji: "\u{1F94F}", name: "flying disc", category: "Activities" },
  { emoji: "\u{1F3B3}", name: "bowling", category: "Activities" },
  { emoji: "\u{1F3CF}", name: "cricket game", category: "Activities" },
  { emoji: "\u{1F3D1}", name: "field hockey", category: "Activities" },
  { emoji: "\u{1F3D2}", name: "ice hockey", category: "Activities" },
  { emoji: "\u{1F94D}", name: "lacrosse", category: "Activities" },
  { emoji: "\u{1F3D3}", name: "ping pong", category: "Activities" },
  { emoji: "\u{1F3F8}", name: "badminton", category: "Activities" },
  { emoji: "\u{1F94A}", name: "boxing glove", category: "Activities" },
  { emoji: "\u{1F94B}", name: "martial arts uniform", category: "Activities" },
  { emoji: "\u{1F945}", name: "goal net", category: "Activities" },
  { emoji: "\u26F3", name: "flag in hole", category: "Activities" },
  { emoji: "\u26F8\uFE0F", name: "ice skate", category: "Activities" },
  { emoji: "\u{1F3A3}", name: "fishing pole", category: "Activities" },
  { emoji: "\u{1F93F}", name: "diving mask", category: "Activities" },
  { emoji: "\u{1F3BD}", name: "running shirt", category: "Activities" },
  { emoji: "\u{1F3BF}", name: "skis", category: "Activities" },
  { emoji: "\u{1F6F7}", name: "sled", category: "Activities" },
  { emoji: "\u{1FA80}", name: "yo yo", category: "Activities" },
  { emoji: "\u{1FA81}", name: "kite", category: "Activities" },
  { emoji: "\u{1F3AF}", name: "bullseye", category: "Activities" },
  { emoji: "\u{1F3B1}", name: "pool 8 ball", category: "Activities" },
  { emoji: "\u{1F52E}", name: "crystal ball", category: "Activities" },
  { emoji: "\u{1F3AE}", name: "video game", category: "Activities" },
  { emoji: "\u{1F579}\uFE0F", name: "joystick", category: "Activities" },
  { emoji: "\u{1F3B0}", name: "slot machine", category: "Activities" },
  { emoji: "\u{1F3B2}", name: "game die", category: "Activities" },
  { emoji: "\u{1F9E9}", name: "puzzle piece", category: "Activities" },
  { emoji: "\u{1F9F8}", name: "teddy bear", category: "Activities" },
  { emoji: "\u265F\uFE0F", name: "chess pawn", category: "Activities" },
  { emoji: "\u{1F0CF}", name: "joker", category: "Activities" },
  { emoji: "\u{1F3B4}", name: "flower playing cards", category: "Activities" },
  { emoji: "\u{1F3AD}", name: "performing arts", category: "Activities" },
  { emoji: "\u{1F3A8}", name: "artist palette", category: "Activities" },
  { emoji: "\u{1F3B5}", name: "musical note", category: "Activities" },
  { emoji: "\u{1F3B6}", name: "musical notes", category: "Activities" },
  { emoji: "\u{1F3B9}", name: "musical keyboard", category: "Activities" },
  { emoji: "\u{1F941}", name: "drum", category: "Activities" },
  { emoji: "\u{1F3B7}", name: "saxophone", category: "Activities" },
  { emoji: "\u{1F3B8}", name: "guitar", category: "Activities" },
  { emoji: "\u{1F3BB}", name: "violin", category: "Activities" },
  { emoji: "\u{1F3BA}", name: "trumpet", category: "Activities" },
  { emoji: "\u{1F3AC}", name: "clapper board", category: "Activities" },

  // ── Objects ──────────────────────────────────────────────
  { emoji: "\u{1F4F1}", name: "mobile phone", category: "Objects" },
  { emoji: "\u{1F4F2}", name: "mobile phone with arrow", category: "Objects" },
  { emoji: "\u260E\uFE0F", name: "telephone", category: "Objects" },
  { emoji: "\u{1F4BB}", name: "laptop", category: "Objects" },
  { emoji: "\u{1F5A5}\uFE0F", name: "desktop computer", category: "Objects" },
  { emoji: "\u{1F5A8}\uFE0F", name: "printer", category: "Objects" },
  { emoji: "\u2328\uFE0F", name: "keyboard", category: "Objects" },
  { emoji: "\u{1F5B1}\uFE0F", name: "computer mouse", category: "Objects" },
  { emoji: "\u{1F4BD}", name: "computer disk", category: "Objects" },
  { emoji: "\u{1F4BF}", name: "optical disk", category: "Objects" },
  { emoji: "\u{1F4C0}", name: "dvd", category: "Objects" },
  { emoji: "\u{1F4F7}", name: "camera", category: "Objects" },
  { emoji: "\u{1F4F8}", name: "camera with flash", category: "Objects" },
  { emoji: "\u{1F4F9}", name: "video camera", category: "Objects" },
  { emoji: "\u{1F3A5}", name: "movie camera", category: "Objects" },
  { emoji: "\u{1F4FD}\uFE0F", name: "film projector", category: "Objects" },
  { emoji: "\u{1F4FA}", name: "television", category: "Objects" },
  { emoji: "\u{1F4FB}", name: "radio", category: "Objects" },
  { emoji: "\u{1F50B}", name: "battery", category: "Objects" },
  { emoji: "\u{1F50C}", name: "electric plug", category: "Objects" },
  { emoji: "\u{1F4A1}", name: "light bulb", category: "Objects" },
  { emoji: "\u{1F526}", name: "flashlight", category: "Objects" },
  { emoji: "\u{1F56F}\uFE0F", name: "candle", category: "Objects" },
  { emoji: "\u{1F4D5}", name: "closed book", category: "Objects" },
  { emoji: "\u{1F4D6}", name: "open book", category: "Objects" },
  { emoji: "\u{1F4D3}", name: "notebook", category: "Objects" },
  { emoji: "\u{1F4D2}", name: "ledger", category: "Objects" },
  { emoji: "\u{1F4C3}", name: "page with curl", category: "Objects" },
  { emoji: "\u{1F4DC}", name: "scroll", category: "Objects" },
  { emoji: "\u{1F4CB}", name: "clipboard", category: "Objects" },
  { emoji: "\u{1F4CC}", name: "pushpin", category: "Objects" },
  { emoji: "\u{1F4CE}", name: "paperclip", category: "Objects" },
  { emoji: "\u{1F4CF}", name: "straight ruler", category: "Objects" },
  { emoji: "\u{1F4D0}", name: "triangular ruler", category: "Objects" },
  { emoji: "\u2702\uFE0F", name: "scissors", category: "Objects" },
  { emoji: "\u{1F4E6}", name: "package", category: "Objects" },
  { emoji: "\u{1F4E7}", name: "email", category: "Objects" },
  { emoji: "\u{1F4E8}", name: "incoming envelope", category: "Objects" },
  { emoji: "\u{1F4E9}", name: "envelope with arrow", category: "Objects" },
  { emoji: "\u{1F4EA}", name: "mailbox", category: "Objects" },
  { emoji: "\u270F\uFE0F", name: "pencil", category: "Objects" },
  { emoji: "\u{1F58A}\uFE0F", name: "pen", category: "Objects" },
  { emoji: "\u{1F58B}\uFE0F", name: "fountain pen", category: "Objects" },
  { emoji: "\u{1F58C}\uFE0F", name: "paintbrush", category: "Objects" },
  { emoji: "\u{1F58D}\uFE0F", name: "crayon", category: "Objects" },
  { emoji: "\u{1F4DD}", name: "memo", category: "Objects" },
  { emoji: "\u{1F50D}", name: "magnifying glass left", category: "Objects" },
  { emoji: "\u{1F50E}", name: "magnifying glass right", category: "Objects" },
  { emoji: "\u{1F50F}", name: "lock with pen", category: "Objects" },
  { emoji: "\u{1F510}", name: "closed lock with key", category: "Objects" },
  { emoji: "\u{1F511}", name: "key", category: "Objects" },
  { emoji: "\u{1F512}", name: "locked", category: "Objects" },
  { emoji: "\u{1F513}", name: "unlocked", category: "Objects" },
  { emoji: "\u{1F528}", name: "hammer", category: "Objects" },
  { emoji: "\u{1FA93}", name: "axe", category: "Objects" },
  { emoji: "\u{1F527}", name: "wrench", category: "Objects" },
  { emoji: "\u{1FA9B}", name: "screwdriver", category: "Objects" },
  { emoji: "\u{1F529}", name: "nut and bolt", category: "Objects" },
  { emoji: "\u2699\uFE0F", name: "gear", category: "Objects" },
  { emoji: "\u{1F9F2}", name: "magnet", category: "Objects" },
  { emoji: "\u{1F52B}", name: "water pistol", category: "Objects" },
  { emoji: "\u{1F4A3}", name: "bomb", category: "Objects" },
  { emoji: "\u{1F9E8}", name: "firecracker", category: "Objects" },
  { emoji: "\u{1FA84}", name: "magic wand", category: "Objects" },
  { emoji: "\u{1F52A}", name: "kitchen knife", category: "Objects" },
  { emoji: "\u{1F6E1}\uFE0F", name: "shield", category: "Objects" },
  { emoji: "\u{1F6AC}", name: "cigarette", category: "Objects" },
  { emoji: "\u26B0\uFE0F", name: "coffin", category: "Objects" },
  { emoji: "\u{1F3FA}", name: "amphora", category: "Objects" },
  { emoji: "\u{1FA9C}", name: "ladder", category: "Objects" },

  // ── Symbols ──────────────────────────────────────────────
  { emoji: "\u2764\uFE0F", name: "red heart", category: "Symbols" },
  { emoji: "\u{1F9E1}", name: "orange heart", category: "Symbols" },
  { emoji: "\u{1F49B}", name: "yellow heart", category: "Symbols" },
  { emoji: "\u{1F49A}", name: "green heart", category: "Symbols" },
  { emoji: "\u{1F499}", name: "blue heart", category: "Symbols" },
  { emoji: "\u{1F49C}", name: "purple heart", category: "Symbols" },
  { emoji: "\u{1F5A4}", name: "black heart", category: "Symbols" },
  { emoji: "\u{1F90E}", name: "brown heart", category: "Symbols" },
  { emoji: "\u{1F90D}", name: "white heart", category: "Symbols" },
  { emoji: "\u{1F49F}", name: "heart decoration", category: "Symbols" },
  { emoji: "\u{1F498}", name: "heart with arrow", category: "Symbols" },
  { emoji: "\u{1F49D}", name: "heart with ribbon", category: "Symbols" },
  { emoji: "\u{1F496}", name: "sparkling heart", category: "Symbols" },
  { emoji: "\u{1F497}", name: "growing heart", category: "Symbols" },
  { emoji: "\u{1F493}", name: "beating heart", category: "Symbols" },
  { emoji: "\u{1F49E}", name: "revolving hearts", category: "Symbols" },
  { emoji: "\u{1F495}", name: "two hearts", category: "Symbols" },
  { emoji: "\u{1F494}", name: "broken heart", category: "Symbols" },
  { emoji: "\u2763\uFE0F", name: "heart exclamation", category: "Symbols" },
  { emoji: "\u{1F4AF}", name: "hundred points", category: "Symbols" },
  { emoji: "\u{1F4A2}", name: "anger symbol", category: "Symbols" },
  { emoji: "\u{1F4A5}", name: "collision", category: "Symbols" },
  { emoji: "\u{1F4AB}", name: "dizzy", category: "Symbols" },
  { emoji: "\u{1F4A6}", name: "sweat droplets", category: "Symbols" },
  { emoji: "\u{1F4A8}", name: "dashing away", category: "Symbols" },
  { emoji: "\u{1F573}\uFE0F", name: "hole", category: "Symbols" },
  { emoji: "\u{1F4AC}", name: "speech balloon", category: "Symbols" },
  { emoji: "\u{1F4AD}", name: "thought balloon", category: "Symbols" },
  { emoji: "\u{1F4A4}", name: "zzz", category: "Symbols" },
  { emoji: "\u{1F6AB}", name: "prohibited", category: "Symbols" },
  { emoji: "\u26A0\uFE0F", name: "warning", category: "Symbols" },
  { emoji: "\u{1F6B7}", name: "no pedestrians", category: "Symbols" },
  { emoji: "\u267B\uFE0F", name: "recycling symbol", category: "Symbols" },
  { emoji: "\u2705", name: "check mark", category: "Symbols" },
  { emoji: "\u274C", name: "cross mark", category: "Symbols" },
  { emoji: "\u274E", name: "cross mark button", category: "Symbols" },
  { emoji: "\u2753", name: "question mark", category: "Symbols" },
  { emoji: "\u2757", name: "exclamation mark", category: "Symbols" },
  { emoji: "\u203C\uFE0F", name: "double exclamation mark", category: "Symbols" },
  { emoji: "\u2049\uFE0F", name: "exclamation question mark", category: "Symbols" },
  { emoji: "\u{1F51F}", name: "keycap 10", category: "Symbols" },
  { emoji: "\u{1F520}", name: "input latin uppercase", category: "Symbols" },
  { emoji: "\u{1F521}", name: "input latin lowercase", category: "Symbols" },
  { emoji: "\u{1F522}", name: "input numbers", category: "Symbols" },
  { emoji: "\u{1F523}", name: "input symbols", category: "Symbols" },
  { emoji: "\u{1F524}", name: "input latin letters", category: "Symbols" },
  { emoji: "\u{1F170}\uFE0F", name: "a button blood type", category: "Symbols" },
  { emoji: "\u{1F18E}", name: "ab button blood type", category: "Symbols" },
  { emoji: "\u{1F171}\uFE0F", name: "b button blood type", category: "Symbols" },
  { emoji: "\u{1F191}", name: "cl button", category: "Symbols" },
  { emoji: "\u{1F192}", name: "cool button", category: "Symbols" },
  { emoji: "\u{1F193}", name: "free button", category: "Symbols" },
  { emoji: "\u{1F194}", name: "id button", category: "Symbols" },
  { emoji: "\u{1F195}", name: "new button", category: "Symbols" },
  { emoji: "\u{1F196}", name: "ng button", category: "Symbols" },
  { emoji: "\u{1F197}", name: "ok button", category: "Symbols" },
  { emoji: "\u{1F198}", name: "sos button", category: "Symbols" },
  { emoji: "\u{1F199}", name: "up button", category: "Symbols" },
  { emoji: "\u{1F19A}", name: "vs button", category: "Symbols" },
  { emoji: "\u{1F504}", name: "counterclockwise arrows", category: "Symbols" },
  { emoji: "\u{1F503}", name: "clockwise vertical arrows", category: "Symbols" },
  { emoji: "\u{1F501}", name: "repeat button", category: "Symbols" },
  { emoji: "\u{1F502}", name: "repeat single button", category: "Symbols" },
  { emoji: "\u25B6\uFE0F", name: "play button", category: "Symbols" },
  { emoji: "\u23E9", name: "fast forward button", category: "Symbols" },
  { emoji: "\u23EA", name: "rewind button", category: "Symbols" },
  { emoji: "\u23F8\uFE0F", name: "pause button", category: "Symbols" },
  { emoji: "\u23F9\uFE0F", name: "stop button", category: "Symbols" },
  { emoji: "\u23FA\uFE0F", name: "record button", category: "Symbols" },
  { emoji: "\u{1F53C}", name: "upwards button", category: "Symbols" },
  { emoji: "\u{1F53D}", name: "downwards button", category: "Symbols" },
  { emoji: "\u27A1\uFE0F", name: "right arrow", category: "Symbols" },
  { emoji: "\u2B05\uFE0F", name: "left arrow", category: "Symbols" },
  { emoji: "\u2B06\uFE0F", name: "up arrow", category: "Symbols" },
  { emoji: "\u2B07\uFE0F", name: "down arrow", category: "Symbols" },
  { emoji: "\u{1F534}", name: "red circle", category: "Symbols" },
  { emoji: "\u{1F7E0}", name: "orange circle", category: "Symbols" },
  { emoji: "\u{1F7E1}", name: "yellow circle", category: "Symbols" },
  { emoji: "\u{1F7E2}", name: "green circle", category: "Symbols" },
  { emoji: "\u{1F535}", name: "blue circle", category: "Symbols" },
  { emoji: "\u{1F7E3}", name: "purple circle", category: "Symbols" },
  { emoji: "\u26AB", name: "black circle", category: "Symbols" },
  { emoji: "\u26AA", name: "white circle", category: "Symbols" },
  { emoji: "\u{1F7E5}", name: "red square", category: "Symbols" },
  { emoji: "\u{1F7E7}", name: "orange square", category: "Symbols" },
  { emoji: "\u{1F7E8}", name: "yellow square", category: "Symbols" },
  { emoji: "\u{1F7E9}", name: "green square", category: "Symbols" },
  { emoji: "\u{1F7E6}", name: "blue square", category: "Symbols" },
  { emoji: "\u{1F7EA}", name: "purple square", category: "Symbols" },
  { emoji: "\u2B1B", name: "black large square", category: "Symbols" },
  { emoji: "\u2B1C", name: "white large square", category: "Symbols" },
  { emoji: "\u{1F536}", name: "large orange diamond", category: "Symbols" },
  { emoji: "\u{1F537}", name: "large blue diamond", category: "Symbols" },
  { emoji: "\u{1F538}", name: "small orange diamond", category: "Symbols" },
  { emoji: "\u{1F539}", name: "small blue diamond", category: "Symbols" },
  { emoji: "\u2728", name: "sparkles", category: "Symbols" },
  { emoji: "\u{1F4A0}", name: "diamond with a dot", category: "Symbols" },
  { emoji: "\u{1F300}", name: "cyclone", category: "Symbols" },
  { emoji: "\u{1F30C}", name: "milky way", category: "Symbols" },
  { emoji: "\u2B50", name: "star", category: "Symbols" },
  { emoji: "\u{1F31F}", name: "glowing star", category: "Symbols" },
  { emoji: "\u{1F320}", name: "shooting star", category: "Symbols" },
  { emoji: "\u2600\uFE0F", name: "sun", category: "Symbols" },
  { emoji: "\u{1F324}\uFE0F", name: "sun behind small cloud", category: "Symbols" },
  { emoji: "\u26C5", name: "sun behind cloud", category: "Symbols" },
  { emoji: "\u{1F325}\uFE0F", name: "sun behind large cloud", category: "Symbols" },
  { emoji: "\u2601\uFE0F", name: "cloud", category: "Symbols" },
  { emoji: "\u{1F327}\uFE0F", name: "cloud with rain", category: "Symbols" },
  { emoji: "\u26C8\uFE0F", name: "cloud with lightning and rain", category: "Symbols" },
  { emoji: "\u{1F329}\uFE0F", name: "cloud with lightning", category: "Symbols" },
  { emoji: "\u26A1", name: "high voltage", category: "Symbols" },
  { emoji: "\u{1F525}", name: "fire", category: "Symbols" },
  { emoji: "\u{1F4A7}", name: "droplet", category: "Symbols" },
  { emoji: "\u{1F30A}", name: "water wave", category: "Symbols" },
  { emoji: "\u{1F308}", name: "rainbow", category: "Symbols" },
  { emoji: "\u2744\uFE0F", name: "snowflake", category: "Symbols" },

  // ── Flags ────────────────────────────────────────────────
  { emoji: "\u{1F3C1}", name: "chequered flag", category: "Flags" },
  { emoji: "\u{1F6A9}", name: "triangular flag", category: "Flags" },
  { emoji: "\u{1F38C}", name: "crossed flags", category: "Flags" },
  { emoji: "\u{1F3F4}", name: "black flag", category: "Flags" },
  { emoji: "\u{1F3F3}\uFE0F", name: "white flag", category: "Flags" },
  { emoji: "\u{1F3F3}\uFE0F\u200D\u{1F308}", name: "rainbow flag", category: "Flags" },
  { emoji: "\u{1F3F3}\uFE0F\u200D\u26A7\uFE0F", name: "transgender flag", category: "Flags" },
  { emoji: "\u{1F1FA}\u{1F1F8}", name: "flag united states", category: "Flags" },
  { emoji: "\u{1F1EC}\u{1F1E7}", name: "flag united kingdom", category: "Flags" },
  { emoji: "\u{1F1E8}\u{1F1E6}", name: "flag canada", category: "Flags" },
  { emoji: "\u{1F1E6}\u{1F1FA}", name: "flag australia", category: "Flags" },
  { emoji: "\u{1F1E9}\u{1F1EA}", name: "flag germany", category: "Flags" },
  { emoji: "\u{1F1EB}\u{1F1F7}", name: "flag france", category: "Flags" },
  { emoji: "\u{1F1EA}\u{1F1F8}", name: "flag spain", category: "Flags" },
  { emoji: "\u{1F1EE}\u{1F1F9}", name: "flag italy", category: "Flags" },
  { emoji: "\u{1F1EF}\u{1F1F5}", name: "flag japan", category: "Flags" },
  { emoji: "\u{1F1F0}\u{1F1F7}", name: "flag south korea", category: "Flags" },
  { emoji: "\u{1F1E8}\u{1F1F3}", name: "flag china", category: "Flags" },
  { emoji: "\u{1F1EE}\u{1F1F3}", name: "flag india", category: "Flags" },
  { emoji: "\u{1F1E7}\u{1F1F7}", name: "flag brazil", category: "Flags" },
  { emoji: "\u{1F1F2}\u{1F1FD}", name: "flag mexico", category: "Flags" },
  { emoji: "\u{1F1F7}\u{1F1FA}", name: "flag russia", category: "Flags" },
  { emoji: "\u{1F1F3}\u{1F1F1}", name: "flag netherlands", category: "Flags" },
  { emoji: "\u{1F1F8}\u{1F1EA}", name: "flag sweden", category: "Flags" },
  { emoji: "\u{1F1F3}\u{1F1F4}", name: "flag norway", category: "Flags" },
  { emoji: "\u{1F1E8}\u{1F1ED}", name: "flag switzerland", category: "Flags" },
  { emoji: "\u{1F1F5}\u{1F1F1}", name: "flag poland", category: "Flags" },
  { emoji: "\u{1F1F5}\u{1F1F9}", name: "flag portugal", category: "Flags" },
  { emoji: "\u{1F1EC}\u{1F1F7}", name: "flag greece", category: "Flags" },
  { emoji: "\u{1F1F9}\u{1F1F7}", name: "flag turkey", category: "Flags" },
  { emoji: "\u{1F1F8}\u{1F1E6}", name: "flag saudi arabia", category: "Flags" },
  { emoji: "\u{1F1EE}\u{1F1F1}", name: "flag israel", category: "Flags" },
  { emoji: "\u{1F1E6}\u{1F1EA}", name: "flag united arab emirates", category: "Flags" },
  { emoji: "\u{1F1F9}\u{1F1ED}", name: "flag thailand", category: "Flags" },
  { emoji: "\u{1F1F8}\u{1F1EC}", name: "flag singapore", category: "Flags" },
  { emoji: "\u{1F1EE}\u{1F1E9}", name: "flag indonesia", category: "Flags" },
  { emoji: "\u{1F1F5}\u{1F1ED}", name: "flag philippines", category: "Flags" },
  { emoji: "\u{1F1FB}\u{1F1F3}", name: "flag vietnam", category: "Flags" },
  { emoji: "\u{1F1F3}\u{1F1FF}", name: "flag new zealand", category: "Flags" },
  { emoji: "\u{1F1E6}\u{1F1F7}", name: "flag argentina", category: "Flags" },
  { emoji: "\u{1F1E8}\u{1F1F4}", name: "flag colombia", category: "Flags" },
  { emoji: "\u{1F1F3}\u{1F1EC}", name: "flag nigeria", category: "Flags" },
  { emoji: "\u{1F1FF}\u{1F1E6}", name: "flag south africa", category: "Flags" },
  { emoji: "\u{1F1EA}\u{1F1EC}", name: "flag egypt", category: "Flags" },
  { emoji: "\u{1F1F0}\u{1F1EA}", name: "flag kenya", category: "Flags" },
  { emoji: "\u{1F1EE}\u{1F1EA}", name: "flag ireland", category: "Flags" },
  { emoji: "\u{1F1E6}\u{1F1F9}", name: "flag austria", category: "Flags" },
  { emoji: "\u{1F1E7}\u{1F1EA}", name: "flag belgium", category: "Flags" },
  { emoji: "\u{1F1E9}\u{1F1F0}", name: "flag denmark", category: "Flags" },
  { emoji: "\u{1F1EB}\u{1F1EE}", name: "flag finland", category: "Flags" },
  { emoji: "\u{1F1FA}\u{1F1E6}", name: "flag ukraine", category: "Flags" },
] as const;

/**
 * Search emoji by name. Returns matching entries.
 */
export function searchEmoji(query: string): readonly EmojiEntry[] {
  if (!query.trim()) return EMOJI_DATA;
  const lower = query.toLowerCase();
  return EMOJI_DATA.filter((entry) => entry.name.toLowerCase().includes(lower));
}

/**
 * Get emoji entries for a specific category.
 */
export function getEmojiByCategory(category: EmojiCategory): readonly EmojiEntry[] {
  return EMOJI_DATA.filter((entry) => entry.category === category);
}

const RECENT_EMOJI_KEY = "openclaw:recent-emoji";
const MAX_RECENT = 24;

/**
 * Load recently used emoji from localStorage.
 */
export function loadRecentEmoji(): string[] {
  try {
    const raw = localStorage.getItem(RECENT_EMOJI_KEY);
    if (!raw) return [];
    const parsed: unknown = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return parsed.filter((item): item is string => typeof item === "string").slice(0, MAX_RECENT);
  } catch {
    return [];
  }
}

/**
 * Save a selected emoji to recents in localStorage.
 * Most recently used appears first, capped at MAX_RECENT.
 */
export function saveRecentEmoji(emoji: string): string[] {
  const current = loadRecentEmoji();
  const filtered = current.filter((e) => e !== emoji);
  const updated = [emoji, ...filtered].slice(0, MAX_RECENT);
  try {
    localStorage.setItem(RECENT_EMOJI_KEY, JSON.stringify(updated));
  } catch {
    // localStorage may be unavailable; silently ignore
  }
  return updated;
}
